nginx:
  image: nginx
  container_name: bxvip_sadmin_nginx
  restart: always
  expose:
    - "80"
  volumes:
    - ./:/usr/share/nginx/html/
    - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
    - /www/bxvip_sadmin/shared/:/www/bxvip_sadmin/shared
  environment:
    - VIRTUAL_HOST=sadmin.bxvip588.com,mysadmin.com
  links:
    - php:php

php:
  image: bxvip_sadmin
  container_name: bxvip_sadmin_php
  restart: always
  expose:
    - "9000"
  volumes:
    - ./:/usr/share/nginx/html
    - ./docker/php/php.ini:/usr/local/etc/php/php.ini:ro
    - /www/bxvip_sadmin/shared/:/www/bxvip_sadmin/shared