<?php
/**
 * Created by IntelliJ IDEA.
 * User: User
 * Date: 18/1/2018
 * Time: 8:04 PM
 */
return [
    array(
        'type'=>1,
        'name'=>'公司入款',
        'sub_type'=>array(
            1=>array(
                'type'=>1,
                'name'=>'银行卡入款',
            ),
            2=>array(
                'type'=>2,
                'name'=>'微信入款',
            ),
            3=>array(
                'type'=>3,
                'name'=>'支付宝入款',
            ),
            4=>array(
                'type'=>4,
                'name'=>'现金转账',
            ),
            5=>array(
                'type'=>5,
                'name'=>'存款优惠',
            ),
            6=>array(
                'type'=>6,
                'name'=>'首存优惠',
            ),
        ),
    ),
    array(
        'type'=>2,
        'name'=>'线上入款',
        'sub_type'=>array(
            1=>array(
                'type'=>1,
                'name'=>'银联入款',
            ),
            2=>array(
                'type'=>2,
                'name'=>'微信扫码入款',
            ),
            3=>array(
                'type'=>3,
                'name'=>'微信app入款',
            ),
            4=>array(
                'type'=>4,
                'name'=>'支付宝扫码入款',
            ),
            5=>array(
                'type'=>5,
                'name'=>'支付宝app入款',
            ),
            6=>array(
                'type'=>6,
                'name'=>'快捷支付',
            ),
            7=>array(
                'type'=>7,
                'name'=>'QQ钱包',
            ),
            8=>array(
                'type'=>8,
                'name'=>'存款优惠',
            ),
            9=>array(
                'type'=>9,
                'name'=>'首存优惠',
            ),
           11=> array(
                'type'=>11,
                'name'=>'QQ钱包App',
            ),
        ),
    ),
    array(
        'type'=>3,
        'name'=>'人工存款',
        'sub_type'=>array(
            1=>array(
                'type'=>1,
                'name'=>'人工存入',
            ),
            2=>array(
                'type'=>2,
                'name'=>'存款优惠',
            ),
            3=>array(
                'type'=>3,
                'name'=>'负数额度清零',
            ),
            4=>array(
                'type'=>4,
                'name'=>'取消出款',
            ),
            5=>array(
                'type'=>5,
                'name'=>'返点优惠',
            ),
            6=>array(
                'type'=>6,
                'name'=>'活动优惠',
            ),
            7=>array(
                'type'=>7,
                'name'=>'汇款优惠',
            ),
            8=>array(
                'type'=>8,
                'name'=>'首存优惠',
            ),
            9=>array(
                'type'=>9,
                'name'=>'其他',
            ),
            10=>array(
                'type'=>10,
                'name'=>'人工撤单',
            ),
        ),
    ),
    array(
        'type'=>4,
        'name'=>'活动优惠',
        'sub_type'=>array(
            array(
                'type'=>1,
                'name'=>'注册活动',
            ),
            array(
                'type'=>2,
                'name'=>'充值活动',
            ),
            array(
                'type'=>3,
                'name'=>'投注活动',
            ),
            array(
                'type'=>4,
                'name'=>'推广活动',
            ),
            array(
                'type'=>5,
                'name'=>'其他活动',
            ),
            array(
                'type'=>6,
                'name'=>'签到活动',
            ),
            array(
                'type'=>7,
                'name'=>'红包活动',
            ),
            array(
                'type'=>8,
                'name'=>'晋级活动',
            ),
        ),
    ),
    array(
        'type'=>5,
        'name'=>'投注退还',
        'sub_type'=>array(
        ),
    ),
    array(
        'type'=>6,
        'name'=>'提款退还',
        'sub_type'=>array(
        ),
    ),
    array(
        'type'=>7,
        'name'=>'代理返点',
        'sub_type'=>array(
            array(
                'type'=>1,
                'name'=>'派送返点',
            ),
        ),
    ),
    array(
        'type'=>9,
        'name'=>'中奖派送',
        'sub_type'=>array(
        ),
    ),
    array(
        'type'=>50,
        'name'=>'提款',
        'sub_type'=>array(
            array(
                'type'=>1,
                'name'=>'线上提出',
            ),
            array(
                'type'=>2,
                'name'=>'人工提款',
            ),
            array(
                'type'=>3,
                'name'=>'误存提出',
            ),
            array(
                'type'=>4,
                'name'=>'现金转账',
            ),
            array(
                'type'=>5,
                'name'=>'重复出款',
            ),
            array(
                'type'=>6,
                'name'=>'会员负数回冲',
            ),
            array(
                'type'=>7,
                'name'=>'手动申请出款',
            ),
            array(
                'type'=>8,
                'name'=>'扣除非法下注派彩',
            ),
            array(
                'type'=>9,
                'name'=>'放弃优惠',
            ),
            array(
                'type'=>10,
                'name'=>'误存提出',
            ),
            array(
                'type'=>11,
                'name'=>'其他',
            ),
            array(
                'type'=>12,
                'name'=>'提款申请',
            )
        ),
    ),
    array(
        'type'=>51,
        'name'=>'投注金额',
        'sub_type'=>array(
        ),
    ),
    array(
        'type'=>52,
        'name'=>'现金交易',
        'sub_type'=>array(
            array(
                'type'=>1,
                'name'=>'代理转入',
            ),
            array(
                'type'=>2,
                'name'=>'代理转出',
            ),
        ),
    ),
];