<?php
namespace app\index\model;
use	think\Model;

/**
DROP TABLE IF EXISTS `api_synthe_table`;
CREATE TABLE `api_synthe_table` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(10) unsigned not null default '' comment '业主id',
  `date` int(8) NOT NULL DEFAULT '0' comment '日期',
  `win_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '每日盈利',
  `win_sum_percent` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '每日盈利率',
  `pay_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '充值总额',
  `pay_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '充值总笔数',
  `pay_pay_odd` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '存款优惠',
  `pay_pay_odd_count` int(10) unsigned NOT NULL COMMENT '存款优惠（笔）',
  `pay_first_odd` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '首存优惠(元)',
  `pay_first_odd_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '首存优惠(笔)',
  `hm_pay_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '人工入款',
  `hm_pay_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '人工入款（笔）',
  `pay_bank_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '银行卡转账',
  `pay_bank_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '银行卡转账(笔)',
  `pay_weixin_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '微信转账',
  `pay_weixin_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '微信转账（笔）',
  `pay_alipay_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '支付宝转账',
  `pay_alipay_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付宝转账(笔)',
  `pay_ol_bank_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '银联入款',
  `pay_ol_bank_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '银联入款(笔)',
  `pay_ol_weixin_qrsum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '微信扫码',
  `pay_ol_weixin_qrcount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '微信扫码(笔)',
  `pay_ol_weixin_appsum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '微信APP存款',
  `pay_ol_weixin_appcount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '微信APP存款(笔)',
  `pay_ol_alipay_qrsum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '支付宝扫码',
  `pay_ol_alipay_qrcount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付宝扫码(笔)',
  `pay_ol_alipay_appsum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '支付宝APP',
  `pay_ol_alipay_appcount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '支付宝APP（笔）',
  `pay_ol_qq_qrsum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT 'QQ扫码',
  `pay_ol_qq_qrcount` int(10) unsigned NOT NULL DEFAULT '0' COMMENT 'QQ扫码（笔）',
  `pay_ol_quick_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '快捷支付',
  `pay_ol_quick_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '快捷支付（支付）',
  `get_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '总提款金额',
  `get_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '总提款笔数',
  `get_ol_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '线上提出',
  `get_ol_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '线上提出笔数',
  `get_hm_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '人工提出',
  `get_hm_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '人工提出（笔）',
  `tk_ret_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '提款退还',
  `tk_ret_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '提款退还（笔）',
  `touzhu_price_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '投注总额',
  `touzhu_price_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '投注总额（笔）',
  `tz_ret_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '撤单总额',
  `tz_ret_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '撤单总额(人）',
  `tz_usefull_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '有效投注',
  `tz_usefull_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '有效投注（笔）',
  `win_price_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '中奖金额',
  `win_price_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '中奖笔数',
  `event_odd_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '总活动礼金',
  `event_odd_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '总活动礼金（笔）',
  `ev_odd_reg_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '注册活动',
  `ev_odd_reg_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '注册活动（笔）',
  `ev_odd_tz_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '投注活动',
  `ev_odd_tz_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '投注活动(笔)',
  `ev_odd_tg_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '推广活动',
  `ev_odd_tg_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '推广活动(笔)',
  `ev_odd_pay_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '充值活动',
  `ev_odd_pay_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '充值活动（笔）',
  `ev_odd_bag_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '红包活动',
  `ev_odd_bag_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '红包活动(笔)',
  `ev_odd_sign_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '签到活动',
  `ev_odd_sign_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '签到活动',
  `ev_odd_rise_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '晋级活动',
  `ev_odd_rise_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '晋级活动(笔）',
  `ev_odd_other_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '其他活动',
  `ev_odd_other_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '其他活动(笔)',
  `daili_gain_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '代理返点',
  `daili_gain_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '代理返点(笔)',
  `trad_money_pay_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '现金转出',
  `trad_money_pay_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '现金转出(笔)',
  `trad_money_get_sum` double(11,4) NOT NULL DEFAULT '0.00' COMMENT '现金转入',
  `trad_money_get_count` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '现金转入(笔)',
  `uid` int(11) NOT NULL DEFAULT '0' COMMENT '用户id,0表示所有',
  `is_deal` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否处理完成',
  `people_pay` text,
  `people_pay_save` text,
  `people_pay_first_odd` text,
  `people_hm_pay` text,
  `people_gs_pay_bank` text,
  `people_gs_pay_weixin` text,
  `people_gs_pay_alipay` text,
  `people_ol_pay_weixin_qr` text,
  `people_ol_pay_weixin_app` text,
  `people_ol_pay_alipay_qr` text,
  `people_ol_pay_alipay_app` text,
  `people_ol_pay_qq_qr` text,
  `people_ol_pay_quick` text,
  `people_pay_first` text,
  `people_get` text,
  `people_get_ol` text,
  `people_get_hm` text,
  `people_get_ret` text,
  `people_touzhu` text,
  `people_touzhu_ret` text,
  `people_win` text,
  `people_ev_all` text,
  `people_ev_reg` text,
  `people_ev_tz` text,
  `people_ev_tg` text,
  `people_ev_pay` text,
  `people_ev_bag` text,
  `people_ev_sign` text,
  `people_ev_rise` text,
  `people_ev_other` text,
  `people_fandian` text,
  `people_trad_pay` text,
  `people_trad_get` text,
  `pay_ol_qq_app_sum` double(10,4) NOT NULL DEFAULT '0.0000',
  `pay_ol_qq_app_count` int(10) NOT NULL DEFAULT '0',
  `people_ol_pay_qq_app` int(10) NOT NULL DEFAULT '0',
  `pay_first_sum` double(10,4) NOT NULL DEFAULT '0.0000',
  `pay_first_count` int(10) NOT NULL DEFAULT '0',
  `pay_qq_sum` double(10,4) NOT NULL DEFAULT '0.0000',
  `pay_qq_count` int(10) NOT NULL DEFAULT '0',
  `people_ol_pay_bank` text,
  PRIMARY KEY (`id`),
  KEY `id` (`id`),
  KEY `user_id` (`user_id`),
  KEY `user&uid` (`user_id`,`uid`),
  KEY `date&user_id` (`user_id`,`date`)
) ENGINE=InnoDB AUTO_INCREMENT=1269 DEFAULT CHARSET=utf8;

 */

class SyntheTable extends Model {
    protected $table = 'api_synthe_table';
    private $cacheName = 'api_synthe_table'; // 缓存名字 方便清除缓存
    private $expire = 60 * 60 * 24; // 默认缓存一天

}